### PR TITLE
Add support for 'asset' filter to Mautic (RR23)

### PR DESCRIPTION
**Pull request by maxlawton**
Adds the 'assets' filter to the EmailBundle and LeadBundle. 

The changes introduced in this PR are probably a good candidate for an upstream PR. However, the branch _rr23-assets-segment-filter_ is based on our _master_, which diverged from _mautic/mautic:master_ before we started using the _develop_ branch, so it may need to be rebased onto the upstream _master_. I'm not sure of the best procedure for doing that given our divergent state.

### CODE REVIEW

**Comment by filipelbc** [comment]
@maxlawton The official Mautic repo has two branches: "master" for the current release, and "staging", which is the target for pull requests there.

Their current staging is 12 commits ahead of their current master.

Since they've had 2 releases since we forked, I would like to propose rebasing our develop branch to their current master. After we fix eventual problems, you could create pull requests there with our changes.

As they accept the merge requests and create a new release, we rebase again.

This assumes some work on cleaning the commit history. But if we get all core changes encapsulated in single commits, it should not be hard.

We also have tests for the most critical changes, so it should be safe. 

What do you think?

**Comment by maxlawton** [comment]
@filipelbc I'm generally somewhat opposed to rebasing published branches, and i'm not sure we need to do that to get their new releases. I propose the following:

1. Hard reset our _master_ to match theirs. This won't lose any history since _develop_ was based on our divergent _master_.
2. Periodically merge _mautic/mautic:master_ into _MauldinEconomics/mautic:master_ to obtain new releases. Never merge our branches into _master_.
3. Merge (our) _master_ into _develop_.
4. When submitting PRs to the upstream (_mautic/mautic_), do so from branches that have been started from or rebased onto _mautic/mautic:master_.

**Comment by maxlawton** [comment]
@filipelbc As for the work that we have in **develop** that is _not_ going to be in PRs to the upstream, I plan to extract our plugins into their own Composer repos once everything is ready for production.

**Comment by filipelbc** [comment]
@maxlawton Your proposal also works.

I think the medium term objective is to make this repo obsolete because everything we need for our custom plugins to work would be merged into the oficial mautic repo. I don't think it would be difficult to also get some plugins to be accepted as a core feature by them. And only the plugins would need to be maintained.

If you agree with me on this, then we only differ on the method:

    rebase develop to our updated master

x

    merge our updated master into develop

I think rebasing let's you better keep track of how many changes are left to get accepted by them, which are not that many in any case. But this is not a strong preference.

As regards how to make the pull requests to upstream, I think the target branch is _mautic/mautic:staging_, although the difference is probably minimal. Otherwise, I agree.

**Comment by maxlawton** [comment]
@filipelbc I think you're correct about _staging_ being the upstream target branch.

I agree on the long-term objective being to make this repo obsolete.

As for rebasing **develop** onto **master**, I see the benefits to doing so. Existing commits that have been merged into **develop** from feature branches (PRs) can be squashed on a per-feature basis and we can delete those merged branches, discarding the obsolete history of the pre-rebase **develop** and its children.

Should we hold off until we can reach a point where ongoing development can be frozen? That may allow us to avoid conflicts (and a confusing duplicate history) with our currently unresolved PRs.

**Comment by filipelbc** [comment]
@maxlawton Exactly!

As far as I can see, we are very near of being feature complete, at least as regards changes to Mautic core. So I think it is reasonable to hold off (until the end of this milestone at least).
We will then have a working stable version for testing, and can safely work on getting the updates from upstream.

As regards contributing to upstream, there is a legal aspect to it.  GG owns the rights to all work from BA, so we would need explicit authorization to share code with the Mautic community.
So, I think when the time comes, you can email us, with Ed and Todd copied, or somehow discuss this with them.

**Pull request merged**
