### PR TITLE
Email click plugin review

### PR DESCRIPTION
**Pull request by maxlawton**
Most of these changes involve the adjustment of the various hard-coded strings used to identify services and events within this plugin. A vendor prefix of `mauldin` has been used in place of `mautic` throughout and prepended to bare names where applicable. These changes have been made to avoid potential collisions with future core additions.

This also introduces some minor removal of unused dependency injections and some very minimal stylistic adjustments.

Acceptance of this PR will satisfy the review of #5.

### CODE REVIEW

**Comment by filipelbc** [comment]
@maxlawton Many thanks for this review, it looks great. I'm just going to run our tests, then give you the feedback.

**Comment by maxlawton** [comment]
Oh right, the tests may have to be updated to reflect the changes.

I tested it manually, but we certainly want the automated testing to pass
before this is accepted.

**Comment by maxlawton** [comment]
I have updated the `email-click-link-add-to-list-camp.feature` to reflect the changes introduced in this PR.

See: https://github.com/MauldinEconomics/csi-unicorn/pull/6

**Comment by filipelbc** [comment]
@maxlawton The tests pass. I think you can merge this and the other branch.

**Pull request merged**
