### PR TITLE
Csi api fix

### PR DESCRIPTION
**Pull request by jojomnky**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| Related user documentation PR URL | no
| Related developer documentation PR URL | https://github.com/MauldinEconomics/csi-unicorn/pull/61
| Issues addressed (#s or URLs) | no
| BC breaks? | no
| Deprecations? | no

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This fixes a bug discovered in production due to the extra API authentication needed there.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Add a contact to a CSI list in production mautic
2. Trigger `app/console mautic:csi:list:update`

### CODE REVIEW

**Comment by filipelbc** [comment]
@jojomnky For local testing, I assume we need to change, for instance, `'optOut/live'` to `'optOut/vagrant'`, right?

**Comment by jojomnky** [comment]
@filipelbc "default" would be good for local testing

**Comment by maxlawton** [comment]
@jojomnky @filipelbc That environment suffix should probably be configured in a container parameter and/or command argument, right?

**Comment by filipelbc** [comment]
@jojomnky @maxlawton I would say so. It can be a configuration parameter on `local.php`.

**Comment by filipelbc** [comment]
@jojomnky @maxlawton I've removed some duplicated code. I think this is good to merge.

The command runs successfully here.

But I wonder whether the changes introduced in this PR have any impact on our current test environment, because it was working before.

How can we setup CSI locally to run as close as possible to how it runs in production?

**Pull request merged**
