### PR TITLE
Email scalability plugin (RR5)

### PR DESCRIPTION
**Pull request by massudaw**
This deprecates #3 and #4 

This is a Work In Progress.

### CODE REVIEW

**Comment by massudaw** [comment]
@maxlawton This is the new pull request for email scalability. it is still WIP but only few chahges in the plugin files are missing. I will close the other pull requests #3 and #4.

**Comment by filipelbc** [comment]
@maxlawton Can I also have write access to this repo?

**Comment by filipelbc** [comment]
@maxlawton I've updated this branch. We do not expect more changes to the files in the plugin, nor to Mautic core.

What is missing now are the changes related to the new dependency in composer.

The dockerization changes will be in the `csi-unicorn` repo.

**Comment by filipelbc** [comment]
@maxlawton I've added the changes to composer.

**Comment by filipelbc** [comment]
@maxlawton There is a caveat, though, when installing locally with composer.

After installing, composer tries to clean the cache, and this raises an error because of the missing rabbitmq parameters in `app/config/local.php`. This should not be a problem, since the library files will be there, and when you start the docker container, they will be used. This `local.php` file is overwritten inside the container when it starts.

If you want to avoid this, just add the rabbitmq parameters to the file, like:

```php
  <?php
  $parameters = array(
	  'db_driver' => 'pdo_mysql',
	  'db_host' => 'mysql',
	  'db_port' => 3306,
	  'db_name' => 'mautic',
	  'db_user' => 'root',
	  'db_password' => 'mautic',
	  'install_source' => 'Docker',
      'rabbitmq_host' => 'rabbitmq',
      'rabbitmq_port' => '5672',
      'rabbitmq_username' => 'guest',
      'rabbitmq_password' => 'guest',
  );
```

I'll add this to the readme in the pull request in csi-unicorn.

**Pull request merged**
