### PR TITLE
Fix not generating email html view

### PR DESCRIPTION
**Pull request by filipelbc**
Depends on #19

### CODE REVIEW

**Comment by filipelbc** [comment]
I've rebased this (the the other branches which depend on this one) to current develop to facilitate the code review.

**Comment by maxlawton** [comment]
Two questions:

1. How does this commit fix the generation of the HTML view?
2. Why does the `mautic.helper.mailer` service no longer need to be the _QueuedMailHelper_ ?

**Comment by filipelbc** [comment]
@maxlawton The "QueuedMailHelper" was created to avoid modifying some core code. Notice that what it does is avoid executing a "problematic" code block when the "transport" is an instance of "QueuedTransportInterface".

Skipping this code block was necessary because it was not allowing to effectively execute more than two "email:send" commands in parallel.

We finally figured out the side-effect of skipping that code block and also found a fix.

That code block was the one which created the "html view" version of the email!

The problem was each command instance was trying to write the same row to the db and conflicting with one another. So the fix was to replace the default "insert" by one which ignores the error if the row already exists.

I hope this is clear. Just ask if you have more questions.

**Comment by maxlawton** [comment]
@filipelbc Ahh, thanks for clarifying. It all makes sense now.

**Pull request merged**
